/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pid.exercise.test;

import org.junit.Test;

import com.sa.pidexercise2.model.JsonModel;
import com.sda.pidexercise2.repository.AttendeeRepository;

import pid.exercise.Library;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    
 
}
